### ISSUE TITLE
Project request: Toki

### ISSUE THREAD

**Issue by purifetchi** [warriordog/DotNet-ActivityPub-Projects#4]
Hi!

For the past month or two I've been developing a C# ActivityPub/Fediverse server called Toki, with custom ActivityPub and ActivityStreams implementations! While not having a front-end (yet), it does feature proper support for the Mastodon API set.

It's come to the point where I feel comfortable sharing it around and it's be a great pleasure for me if I could get it on the list too :)

The link to the repository is here: https://github.com/purifetchi/Toki

Thank you for your time!

**Comment by warriordog** [comment]
thanks for the link, I'll take a look!

**Comment by warriordog** [comment]
@purifetchi done, Toki has been added. please let me know if there's any mistakes or errors!

**Comment by warriordog** [comment]
@purifetchi btw, nice work! Toki is a really cool project

**Comment by purifetchi** [comment]
Thank you!! ^^
